config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  get 'users/profile'

  root 'welcome#index'
  get '/users/profile', as: 'user_root'

  resources :users do
    resources :articles do
  	  resources :comments
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?# Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
  end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	 # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :authenticate_user!
	def index
    	@articles = Article.where(:user_id => current_user.id)
  end

	def show
   	 	@article = Article.find(params[:id])
      @user = User.find(params[:user_id])
      @comment = Comment.new
  end

	def new
  		@article = Article.new
	end

	def edit
    @user = User.find(params[:user_id])
		@article = Article.find(params[:id])
	end

	def create
    @user = User.find(params[:user_id])
 		@article = @user.articles.create(article_params)

  		if @article.save
    			redirect_to @user
  		else
    			render '_form'
  		end
	end
	
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render "edit"
		end
	end

	
  def destroy
    @article =  Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	private
  		def article_params
    		params.require(:article).permit(:title, :text, :sender)
  		end
	end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  before_action :authenticate_user!
  def index
    @article = Article.find(params[:article_id])
    @user = @article.sender
  end

  def create
    @user = current_user[:id]
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to user_article_path(@user, @article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @user = @article[:user_id]
    @comment.destroy 
    redirect_to user_article_path(@user, @article)
  end

  private
    def comment_params
	params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/update_controller.rb
def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end
 
def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end
 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    	@users = User.all
  end

  def profile
    @user = User.new
    @article = Article.new
    redirect_to current_user
  end

	def show
   	 	@user = User.find(params[:id])
      @article = Article.new
 	end

	def new
  		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
 		@user = User.new(user_params)
 
  		if @user.save
    			redirect_to @user
  		else
    			render 'new'
  		end
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user
		else
			render "edit"
		end
	end

	
     	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private
  		def user_params
    		params.require(:user).permit(:id, :name)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<% @path =  article.user_id.to_s + "/articles/" + article[:id].to_s %>
<p>
    <%= article.sender %> sayd:
    <%=link_to article.title, @path, method: :get%>

</p>

<p>
    <strong>Text:</strong>
    <%= article.text %>

</p>

app/views/articles/_form.html.erb
<%= form_for ([@user, @user.articles.build])  do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
    <%= f.hidden_field :sender, :value => current_user.name %>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', user_path(@user) %>

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New article', new_article_path %>
<button class = 'abcsort'>Sort by alphabet</button>
<button class = 'timesort'>Sort by creation time</button>	
<% if cookies[:sort] == 'abc' %>
  <% @articles = Article.all.sort_by { |item|%>
    <% item[:title]%>
  <% } %>
<% end %>
<% if cookies[:sort] == 'time' %>
  <% @articles = Article.all.sort_by { |item|%>
    <% item[:created_at] %>
  <% } %>
<% end %>

<table class = "tb">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan = "3"></th>
  </tr> 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to "Show ", article_path(article) %></td>
      <td><%= link_to "Edit ", edit_article_path(article) %></td>
      <td><%= link_to "Destroy", article_path(article), 
	      method: :delete,
	      data: {confirm: "Are you sure?"} %></td> 
   </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<= render 'form' %>
 
<= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if request.url != "http://localhost:3000/users/" + @article.user_id.to_s + "/articles/" + @article[:id].to_s %>
    <%= render 'article' %>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<% if @article.comments.exists?%>
    <h2>Comments:</h2>
    <%= render @article.comments %>
<% end %>


<h2>Add a comment:</h2>
<% @url = @article.id.to_s + "/comments" %>
<%= form_for(@comment, :url => @url) do |f| %>
    <%= f.hidden_field :commenter, :value => @user.name %>
    <p>
        <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', user_path(@user) %> |
<%= link_to 'Edit', edit_user_article_path(@user, @article) %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter%>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<% @url = '/users/' + @user.id.to_s + '/articles/' + @article.id.to_s + '/comments/' + comment.id.to_s %>
<p>
  <%= link_to 'Destroy Comment', @url,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<% @url = "users/" + current_user[:id].to_s + "/articles/" + @article.id.to_s + "/comments" %>
<%= form_for(@comment, :url => @url) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :pass %><br>
    <%= f.password_field :pass %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>User list</h1>
    <% @users.each do |user| %>
      <%= link_to user.email, user_path(user) %><br>

  <%end%>

app/views/users/profile.html.erb
<h1>My profile</h1>

<%=link_to 'users', users_path%>

<h2>Articles</h2>
<%=render @user.articles %>

<h2>Add article:</h2>
<%= render 'articles/form' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/users/show.html.erb
    <% if current_user.id == @user.id %>
        <h1>My profile</h1>
    <% else %>
        <h1><%=@user.name%>'s profile</h1>
    <% end %>
    <%= link_to 'exit', destroy_user_session_path, :method => :delete %><br>
    <%=link_to 'users', users_path%>

    <% if @user.articles.exists?%>
        <h2>Articles</h2>
        <%= render @user.articles %>
    <% end %>


    <h2>Add article:</h2>
    <%= render 'articles/form' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

app/views/welcome/index.html.erb
<h1>Hi, user </h1>

<% if user_signed_in? %>
    <span> hi, <%= current_user.email %></span>
    <%= link_to 'exit', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'enter', new_user_session_path %> or <%= link_to 'registration', new_user_registration_path %>
<% end %>